version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=pejovski
      - RABBITMQ_DEFAULT_PASS=pejovski
      - RABBITMQ_ERLANG_COOKIE="fdas98uf89d9fda1865fdas"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  rabbitmqdata:
    driver: local



